<a href="https://colab.research.google.com/github/ProxCentauri/Python-Tutorials-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is NumPy?**

NumPy stands for Numerical Python.

It's a library for numerical computing with powerful support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Use cases include scientific computing, data analysis, and machine learning.

In [1]:
pip install numpy

In [2]:
import numpy as np
print(np.__version__)

1.26.4


# **Creating NumPy Arrays:**
**from Python List**

In [3]:
arr = np.array([1, 2, 3])

**Array Attributes:**

Shape, size, and data type

In [4]:
print(arr.shape)  # (3,)
print(arr.size)   # 3
print(arr.dtype)  # int64 (may vary)

(3,)
3
int64


# **Array Initialization:**

Zeros:

In [5]:
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ones:

In [6]:
ones_arr = np.ones((2, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


Full:

In [7]:
full_arr = np.full((2, 3), 7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


Arange:

In [8]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


Linspace:

In [9]:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


Random:

In [ ]:
random_arr = np.random.random((3, 3))
print(random_arr)

In [10]:
#Example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64


# **Basic Operations**

**Element-wise Operations**

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add = arr1 + arr2
subtract = arr1 - arr2
multiply = arr1 * arr2
divide = arr1 / arr2

print("Add:", add)
print("Subtract:", subtract)
print("Multiply:", multiply)
print("Divide:", divide)

Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]


**Basic Mathematical Functions**

In [12]:
sum_arr = np.sum(arr1)
mean_arr = np.mean(arr1)
median_arr = np.median(arr1)
std_arr = np.std(arr1)

print("Sum:", sum_arr)
print("Mean:", mean_arr)
print("Median:", median_arr)
print("Standard Deviation:", std_arr)

Sum: 6
Mean: 2.0
Median: 2.0
Standard Deviation: 0.816496580927726


**Array Broadcasting:**

Broadcasting allows for arithmetic operations on arrays of different shapes.

In [13]:
arr = np.array([1, 2, 3])
scalar = 2
result = arr * scalar
print(result)  # [2, 4, 6]

[2 4 6]


# **Indexing and Slicing**

**Basic Indexing**

In [14]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 10
print(arr[-1])  # 50

10
50


**Slicing**

In [15]:
print(arr[1:4])  # [20, 30, 40]
print(arr[:3])  # [10, 20, 30]
print(arr[::2])  # [10, 30, 50]

[20 30 40]
[10 20 30]
[10 30 50]


**Boolean Indexing**

In [16]:
print(arr[arr > 30])  # [40, 50]

[40 50]


**Fancy Indexing**

In [17]:
indices = [0, 2, 4]
print(arr[indices])  # [10, 30, 50]

[10 30 50]


In [18]:
#example
arr = np.arange(10)
print(arr)
print(arr[2:7])
print(arr[arr % 2 == 0])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[0 2 4 6 8]


#**Reshaping and Resizing**

In [19]:
#Reshaping Arrays
arr = np.arange(6)
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)

[[0 1 2]
 [3 4 5]]


In [20]:
#Flattening Arrays
flattened_arr = reshaped_arr.ravel()
print(flattened_arr)

[0 1 2 3 4 5]


# **Concatenation and Stacking**

In [21]:
#Concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


In [22]:
#Vertical Stack
stacked_arr_v = np.vstack((arr1, arr2))
print(stacked_arr_v)

[[1 2 3]
 [4 5 6]]


In [23]:
#Horizontal Stack
stacked_arr_h = np.hstack((arr1, arr2))
print(stacked_arr_h)

[1 2 3 4 5 6]


In [24]:
#example
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)

[[1 2]
 [3 4]
 [5 6]]
